apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv2
  labels:
    app: mongo-db
spec:
  capacity:
    storage: 2Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mongo-jobmgr   # Docker Desktop/Minikube hostPath inside the VM
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc2
  namespace: jobmgr
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: mongo-db
